baseURL = 'https://hcank4.github.io/Project-LapTrinhMang/'
languageCode = 'vi'
title = 'Blog Lập Trình Mạng'
theme = 'PaperMod'

[params]
  author = "Hong Can" 
  description = "Chia sẻ kiến thức Java & JavaScript"
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang Chủ"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Bài Viết"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "Giới Thiệu"
    url = "/about/"
    weight = 30
  [params.profileMode]
    enabled = true
    title = "Chào bạn, mình là Hồng Cần!"
    subtitle = "Sinh viên CNTT | Đam mê lập trình Java & Web Development"
    displayFullContent = true
    imageUrl = "https://github.com/hcank4.png" # Lấy ảnh đại diện từ GitHub của bạn
    imageTitle = "Avatar"
    imageWidth = 120
    imageHeight = 120

    [[params.profileMode.buttons]]
        name = "Xem các bài viết"
        url = "posts"

    [[params.profileMode.buttons]]
        name = "GitHub cá nhân"
        url = "https://github.com/hcank4"
    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/hcank4"
[[params.socialIcons]]
    name = "facebook"
    url = "https://facebook.com/your-profile"
[[params.socialIcons]]
    name = "email"
    url = "mailto:your-email@gmail.com"