baseURL = 'https://hcank4.github.io/Project-LapTrinhMang/'
languageCode = 'vi'
title = 'Hồng Cần Portfolio'
theme = 'PaperMod'

[pagination]
    pagerSize = 20

[markup.goldmark.renderer]
    unsafe = true  # Bắt buộc phải có để chạy HTML/CSS tùy chỉnh cho trang chủ

[params]
    author = "Hong Can" 
    description = "Software Developer & Portfolio"
    # Sửa thành "light" để có nền trắng, chữ đen giống mẫu Wix
    defaultTheme = "light" 
    ShowCodeCopyButtons = true 

[params.profileMode]
    enabled = false  # Đã sửa lỗi chính tả "flase" thành "false"
    # Tắt cái này để dùng layout tùy chỉnh giống mẫu image_dec0df.jpg

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/hcank4"

[[params.socialIcons]]
    name = "facebook"
    url = "https://www.facebook.com/hongcan.pham.5070" 

[[params.socialIcons]]
    name = "email"
    url = "mailto:canpham522@gmail.com"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "HOME"
        url = "/"
        weight = 10
    [[menu.main]]
        identifier = "about"
        name = "ABOUT"
        url = "/about/"
        weight = 20
    [[menu.main]]
        identifier = "posts"
        name = "BLOG"
        url = "/posts/"
        weight = 30