baseURL = 'https://hcank4.github.io/Project-LapTrinhMang/'
languageCode = 'vi'
title = 'Blog L·∫≠p Tr√¨nh M·∫°ng'
theme = 'PaperMod'

[params]
    author = "Hong Can" 
    description = "Chia s·∫ª ki·∫øn th·ª©c Java & JavaScript"
    # B·∫°n c√≥ th·ªÉ ƒë·ªïi th√†nh "dark" n·∫øu mu·ªën web lu√¥n c√≥ m√†u ƒëen cho ng·∫ßu
    defaultTheme = "auto" 
    ShowCodeCopyButtons = true 

[params.profileMode]
    enabled = true
    title = "Ch√†o b·∫°n, m√¨nh l√† H·ªìng C·∫ßn! üëã"
    subtitle = "Sinh vi√™n CNTT | ƒêam m√™ l·∫≠p tr√¨nh Java & Web Development"
    displayFullContent = true
    imageUrl = "https://github.com/hcank4.png"
    imageTitle = "Avatar"
    imageWidth = 150
    imageHeight = 150

    [[params.profileMode.buttons]]
        name = "Xem c√°c b√†i vi·∫øt"
        url = "posts"

    [[params.profileMode.buttons]]
        name = "GitHub c√° nh√¢n"
        url = "https://github.com/hcank4"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/hcank4"

[[params.socialIcons]]
    name = "facebook"
    url = "https://www.facebook.com/hongcan.pham.5070" 

[[params.socialIcons]]
    name = "email"
    url = "mailto:canpham522@gmail.com" # ƒê√£ th√™m mailto: ƒë·ªÉ b·∫•m v√†o l√† m·ªü tr√¨nh so·∫°n mail

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Trang Ch·ªß"
        url = "/"
        weight = 10
    [[menu.main]]
        identifier = "posts"
        name = "B√†i Vi·∫øt"
        url = "/posts/"
        weight = 20
    [[menu.main]]
        identifier = "about"
        name = "Gi·ªõi Thi·ªáu"
        url = "/about/"
        weight = 30